### ISSUE TITLE
index error too many indices for array

### ISSUE THREAD

**Issue by Froodrice** [ComputationalEcologyLab/CDPOP#1]
Hi Dr. Landguth,
When running CDPOP (CDPOP Release 2015.02.09-00:00:00MST Version version 1.2.25), I get the following error when attempting to include Male or Female philopatry (screen shot attached).
![python error](https://cloud.githubusercontent.com/assets/20251814/17315743/12449f9c-5823-11e6-8a0f-92a93d6de1dd.png)

Runs with Philopatry=N work without error.
CDPOP produces the grid0.csv file for philopatry but errors afterwards. 
The only change between my inputvars.csv files is the philopatry option.

If they are of use, I am happy to email my initialization and inputvars files for trouble shooting (though they are large files (>1Gb).

Thanks for your time,
Stephen Rice (srice001@ucr.edu)

**Comment by ComputationalEcologyLab** [comment]
Hi Stephen,

Sorry for the slow response, I don't often check in with this email.

Yes, please send me your input files for testing on my end. You can also
chop off the cost matrix and XY points to say a 10 x 10 for testing
purposes too if that is helpful for sending files.

The philopatry module is super picking, so I should be able to spot
relatively quickly what is going on.
Thanks for sending error message,
Erin.
